name: Other Coursework
description: Coursework which doesn't have defined learning objectives or require a submission
title: "<title>"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to assign this coursework!

        Not all of our coursework will fit into the templates for technical or professional development coursework. If an activity does not have clearly defined learning objectives or does not require a submission to be reviewed by a volunteer (eg. signing up for a platform like GitHub) you can use this template.

        To support our trainees with planning and prioritising their own learning journey, we want our coursework assignments to be as informative as possible.
        We don't just want to tell them what to do, we want to tell them stuff like:
        - why we are doing it
        - what it's "for" (problem-solving, debugging, etc)
        - how to submit their work
  - type: textarea
    attributes:
      label: Why are we doing this?
      description: |
        Clearly explain the purpose of this assignment.
        Include links, etc to additional resources if required.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Submission & Review
      description: |
        State in clear steps how a trainee can submit this assignment if they need to submit anything.
        Include guidance for trainees to check if they have completed the task, eg. "You will receive an email confirming account creation".
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Thank you so much.**

        Please now complete this ticket by filling in the options on the sidebar.

        1. Assign the task's priority
        - `Setup` -- Something which should be done before any other tasks in a sprint, eg. registering an account
        - `Recurring` -- Something which will happen in more than one sprint in this module
        - `Core` -- A mandatory task which should be completed by all trainees. These tasks are designed to reinforce the module's success criteria.
        - `Optional` -- An optional task which trainees can attempt after completing other activities. These tasks can further reinforce the success criteria but should not be the only time a concept is covered in a sprint. 
        2. Add a Sprint label to add to the backlog view
        - Sprints are numbered 1-5, depending on the module
        - Multiple sprint labels can be assigned for recurring tasks
        3. Add a submission label to the task. 
        - `PR` -- Trainees will create a pull request for review by a volunteer.
        - `Slack` -- Trainees post a message in their class Slack channel for discussion and/or feedback
        - `Issue` -- Trainees update their copy of this ticket with the required information
        - `None` -- No submission necessary. This label should be used for tasks which do not require review by a volunteer, eg. Codewars exercises

        Once your ticket is complete, you may like to add it to the example project board attached to this repo. This will let you see how it will appear to trainees when they copy the issue to their own planners. If necessary you can make changes using the `Edit` button.
